# Generated by Django 4.2.3 on 2023-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
