# Generated by Django 4.2.3 on 2023-07-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
